/**
 * The icon subset (SH5): dashboard/js/icons.js, generated by scripts/build-icons.mjs, in place
 * of the full 398KB Lucide UMD from the CDN.
 *
 * Four claims, each of which fails silently in the browser if it is wrong:
 *
 *   1. Every icon the dashboard can ask for is in the subset. A miss does not blank the icon
 *      (the fallback below catches it), but it quietly puts the 93KB download back.
 *   2. The shim renders what lucide@0.577.0 rendered: the same svg attributes, the same
 *      `lucide lucide-<name>` class, `data-lucide` kept — the stylesheet sizes every icon
 *      through `[data-lucide]` and mirrors the directional ones through it too.
 *   3. A name the subset lacks loads the pinned UMD exactly once, with its SRI hash, and
 *      then draws the missing icons with it.
 *   4. `build-icons.mjs --check` fails when icons.js is stale — and passes when it is not,
 *      because a guard that always fails is as useless as one that never does.
 *
 * Claims 2 and 4 compare against the real UMD, which build-icons.mjs reads from
 * node_modules/.cache (downloading it once, SRI-verified, when it is not there yet).
 */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, before, describe, it } from 'node:test';
import vm from 'node:vm';

type Json = Record<string, any>;
const build: Json = await import(new URL('../../scripts/build-icons.mjs', import.meta.url).href);

const ICONS_JS = 'dashboard/js/icons.js';
const SVG_NS = 'http://www.w3.org/2000/svg';
const XHTML_NS = 'http://www.w3.org/1999/xhtml';

// ─── A DOM just large enough for createIcons ────────────────────────────────

class FakeNode {
    nodeType = 1;
    parentNode: FakeNode | null = null;
    childNodes: FakeNode[] = [];
    attrs: Array<{ name: string; value: string }> = [];
    onload: (() => void) | null = null;
    onerror: (() => void) | null = null;
    constructor(readonly tagName: string, readonly namespaceURI: string | null) {}

    get attributes(): Array<{ name: string; value: string }> { return this.attrs; }
    getAttribute(name: string): string | null { return this.attrs.find((a) => a.name === name)?.value ?? null; }
    setAttribute(name: string, value: string): void {
        const hit = this.attrs.find((a) => a.name === name);
        if (hit) hit.value = String(value);
        else this.attrs.push({ name, value: String(value) });
    }
    appendChild(child: FakeNode): FakeNode {
        if (child.parentNode) child.parentNode.removeChild(child);
        child.parentNode = this;
        this.childNodes.push(child);
        return child;
    }
    removeChild(child: FakeNode): FakeNode {
        this.childNodes = this.childNodes.filter((c) => c !== child);
        child.parentNode = null;
        return child;
    }
    replaceChild(next: FakeNode, old: FakeNode): FakeNode {
        const at = this.childNodes.indexOf(old);
        assert.ok(at !== -1, 'replaceChild: old is a child');
        if (next.parentNode) next.parentNode.removeChild(next);
        this.childNodes[at] = next;
        next.parentNode = this;
        old.parentNode = null;
        return old;
    }
    /** `[attr]` selectors only: all the shim asks for, and all the real createIcons does. */
    querySelectorAll(selector: string): FakeNode[] {
        const attr = selector.match(/^\[([\w-]+)\]$/)?.[1];
        if (!attr) return selector === 'template' ? [] : assert.fail(`unsupported selector ${selector}`);
        const out: FakeNode[] = [];
        const visit = (n: FakeNode): void => {
            for (const c of n.childNodes) {
                if (c.getAttribute(attr) !== null) out.push(c);
                visit(c);
            }
        };
        visit(this);
        return out;
    }
    get outerHTML(): string {
        const attrs = this.attrs.map((a) => ` ${a.name}="${a.value}"`).join('');
        return `<${this.tagName.toLowerCase()}${attrs}>${this.childNodes.map((c) => c.outerHTML).join('')}</${this.tagName.toLowerCase()}>`;
    }
}

interface Dom {
    document: Json;
    body: FakeNode;
    head: FakeNode;
    /** `<i …attrs>` inside a new <div> in <body>; returns the div. */
    icon(attrs: Record<string, string>): FakeNode;
}

function makeDom(): Dom {
    const html = new FakeNode('HTML', XHTML_NS);
    const head = html.appendChild(new FakeNode('HEAD', XHTML_NS));
    const body = html.appendChild(new FakeNode('BODY', XHTML_NS));
    const document: Json = {
        nodeType: 9,
        documentElement: html, head, body,
        createElement: (tag: string) => new FakeNode(tag.toUpperCase(), XHTML_NS),
        createElementNS: (ns: string, tag: string) => new FakeNode(tag, ns),
        querySelectorAll: (selector: string) => {
            const all = html.querySelectorAll(selector);
            return html.getAttribute('data-lucide') !== null ? [html, ...all] : all;
        },
    };
    // A document is the top of the tree: parentNode of <html> is the document.
    (html as unknown as { parentNode: unknown }).parentNode = document;
    const icon = (attrs: Record<string, string>): FakeNode => {
        const div = body.appendChild(new FakeNode('DIV', XHTML_NS));
        const i = div.appendChild(new FakeNode('I', XHTML_NS));
        for (const [k, v] of Object.entries(attrs)) i.setAttribute(k, v);
        return div;
    };
    return { document, body, head, icon };
}

interface Page {
    ctx: Json;
    dom: Dom;
    warnings: string[];
    lucide(): { createIcons(options?: Json): void; subset: string[] };
}

/** icons.js (or another build of it) in a fresh context over a fresh DOM. */
function loadShim(source = readFileSync(ICONS_JS, 'utf8')): Page {
    const dom = makeDom();
    const warnings: string[] = [];
    const ctx: Json = {
        document: dom.document,
        console: { ...console, warn: (...args: unknown[]) => { warnings.push(args.map(String).join(' ')); } },
    };
    ctx.window = ctx;
    ctx.globalThis = ctx;
    vm.createContext(ctx);
    vm.runInContext(source, ctx, { filename: ICONS_JS });
    return { ctx, dom, warnings, lucide: () => ctx.lucide };
}

/** The real lucide@0.577.0 in a fresh context over a fresh DOM. */
async function loadReal(): Promise<Page> {
    const umd: Buffer = await build.loadUmd();
    const dom = makeDom();
    const warnings: string[] = [];
    const ctx: Json = { document: dom.document, console: { ...console, warn: (...a: unknown[]) => { warnings.push(a.map(String).join(' ')); } } };
    ctx.window = ctx;
    ctx.globalThis = ctx;
    vm.createContext(ctx);
    vm.runInContext(umd.toString('utf8'), ctx, { filename: 'lucide.min.js' });
    return { ctx, dom, warnings, lucide: () => ctx.lucide };
}

/** An element as a comparable value: tag, namespace, attribute SET, children. */
function shape(n: FakeNode): Json {
    return {
        tag: n.tagName.toLowerCase(),
        ns: n.namespaceURI,
        attrs: Object.fromEntries([...n.attrs].sort((a, b) => (a.name < b.name ? -1 : 1)).map((a) => [a.name, a.value])),
        children: n.childNodes.map(shape),
    };
}

const subsetOf = (source: string): string[] => {
    const block = source.match(/var ICONS = \{\n([\s\S]*?)\n {4}\};/);
    assert.ok(block, 'icons.js has an ICONS table');
    return [...block[1]!.matchAll(/^ {8}"([a-z0-9-]+)":/gm)].map((m) => m[1]!);
};

// ─────────────────────────────────────────────────────────────────────────────

describe('icon subset — what the collector finds is what icons.js carries', () => {
    const found: Map<string, string> = build.collectIconNames();
    const source = readFileSync(ICONS_JS, 'utf8');
    const subset = subsetOf(source);

    it('every icon name the collector finds is in icons.js, and nothing else is', () => {
        assert.ok(found.size >= 100, `the collector found ${found.size} names — a broken rule finds almost none`);
        const missing = [...found.keys()].filter((n) => !subset.includes(n));
        assert.deepEqual(missing, [], `used but not in ${ICONS_JS}: ${missing.map((n) => `${n} (${found.get(n)})`).join(', ')}`);
        assert.deepEqual(subset.filter((n) => !found.has(n)), [], 'in icons.js but used nowhere');
        assert.deepEqual(subset, [...subset].sort(), 'sorted, so a rebuild diff is only the change');
        assert.deepEqual([...loadShim().lucide().subset], subset, 'the runtime carries the same table');
    });

    it('each collection rule sees its case, and a compared-against literal is not an icon', () => {
        const root = mkdtempSync(join(tmpdir(), 'icons-collect-'));
        try {
            mkdirSync(join(root, 'dashboard/js/pages'), { recursive: true });
            mkdirSync(join(root, 'public'), { recursive: true });
            writeFileSync(join(root, 'dashboard/index.html'), '<div class="login-mark"><i data-lucide="axe" aria-hidden="true"></i></div>');
            writeFileSync(join(root, 'dashboard/js/pages/fixture.js'), [
                "const Page = {",
                "    CALLOUTS: Object.freeze({ tip: 'anchor', note: 'anvil' }),",
                "    kindIcon(kind) { if (kind === 'a') return 'apple'; return 'banana'; },",
                "    risk(k) { return { risky: k.length < 2, reason: 'short' }; },",
                "    tab(key, href, icon, label) { return html`<i data-lucide=\"${icon}\"></i> ${label}`; },",
                "    render(kind, k, ok) {",
                "        const icon = kind === 'video' ? 'film'",
                "            : kind === 'carousel' ? 'images' : 'image';",
                "        const icons = { all: 'layers', failed: 'alert-triangle' };",
                "        return html`",
                "            <i data-lucide=\"${this.CALLOUTS[kind]}\"></i>",
                "            <i data-lucide=\"${this.kindIcon(kind)}\"></i>",
                "            <i data-lucide=\"${this.risk(k).risky ? 'bell' : 'bike'}\"></i>",
                "            <i data-lucide=\"${a.icon || 'file-text'}\"></i>",
                "            ${this.tab('home', '#/x', 'book', t('x.y'))}",
                "            ${UI.button({ icon: icons[kind], variant: 'ghost' })}",
                "            ${Admin.confirm({ confirmIcon: 'bus', tone: 'danger' })}`;",
                "    },",
                "};",
                "el.setAttribute('data-lucide', ok ? 'cake' : 'camera');",
                "// data-lucide=\"${comment}\" is ignored because it has no literals",
            ].join('\n'));
            // A public page that does not run the dashboard's scripts is not scanned.
            writeFileSync(join(root, 'public/landing.html'), '<i data-lucide="castle"></i>');
            const found: Map<string, string> = build.collectIconNames(root);
            assert.deepEqual([...found.keys()], [
                'alert-triangle', 'anchor', 'anvil', 'apple', 'axe', 'banana', 'bell', 'bike', 'book', 'bus',
                'cake', 'camera', 'file-text', 'film', 'image', 'images', 'layers',
            ]);
            assert.match(found.get('axe')!, /^dashboard\/index\.html:1 \(data-lucide\)$/);
            assert.match(found.get('anchor')!, /data-lucide expression → CALLOUTS/);
            assert.match(found.get('apple')!, /data-lucide expression → kindIcon/);
            assert.match(found.get('book')!, /tab\(\) argument 3/);
            assert.match(found.get('bus')!, /confirmIcon/);
            assert.match(found.get('layers')!, /icon → icons/);
            assert.match(found.get('cake')!, /setAttribute/);
            // …and in the real source, the same rules reach the real cases.
            const real: Map<string, string> = build.collectIconNames();
            assert.match(real.get('globe') ?? '', /privacyIcon/, 'this.privacyIcon(level) in posts.js');
            assert.match(real.get('award') ?? '', /emptyState\(\) argument 1/, 'Admin.emptyState(icon, …)');
            assert.match(real.get('rocket') ?? '', /help-content\.js:\d+ \(icon\)/, 'an article icon');
            for (const word of ['video', 'ghost', 'short', 'examples', 'ai']) assert.equal(real.has(word), false, word);
        } finally {
            rmSync(root, { recursive: true, force: true });
        }
    });

    it('index.html loads icons.js where the CDN tag was, and nothing from the CDN', () => {
        const index = readFileSync('dashboard/index.html', 'utf8').replace(/<!--[\s\S]*?-->/g, '');
        const scripts = [...index.matchAll(/<script\b[^>]*\bsrc="([^"]+)"[^>]*>/g)].map((m) => m[0]);
        assert.match(scripts[0] ?? '', /^<script defer src="\/dashboard\/js\/icons\.js\?v=[\w.]+">$/,
            'icons.js is the first deferred script, so it has run before app.js boots');
        assert.ok(scripts.findIndex((s) => s.includes('/js/app.js')) > 0);
        assert.equal(/cdn\.jsdelivr\.net|unpkg\.com|lucide\.min\.js/.test(index), false, 'no CDN script or preconnect left in the shell');
        assert.ok(source.includes(JSON.stringify(build.LUCIDE_URL)) && source.includes(JSON.stringify(build.LUCIDE_SRI)),
            'the fallback carries the pinned URL and SRI');
        // The fallback needs the CDN in the CSP, in both places it is declared.
        for (const file of ['vercel.json', 'src/routes/api.ts']) {
            assert.ok(readFileSync(file, 'utf8').includes('https://cdn.jsdelivr.net'), `${file} still allows the fallback`);
        }
    });
});

describe('icon subset — the shim renders what lucide@0.577.0 rendered', () => {
    it('turns <i data-lucide="check" aria-hidden="true" class="x"> into lucide’s svg', () => {
        const page = loadShim();
        const host = page.dom.icon({ 'data-lucide': 'check', 'aria-hidden': 'true', class: 'x' });
        page.lucide().createIcons({ nodes: [host] });
        assert.equal(host.childNodes.length, 1);
        const svg = host.childNodes[0]!;
        assert.equal(svg.tagName, 'svg');
        assert.equal(svg.namespaceURI, SVG_NS);
        assert.deepEqual(shape(svg).attrs, {
            'aria-hidden': 'true',
            class: 'lucide lucide-check x',
            'data-lucide': 'check',
            fill: 'none',
            height: '24',
            stroke: 'currentColor',
            'stroke-linecap': 'round',
            'stroke-linejoin': 'round',
            'stroke-width': '2',
            viewBox: '0 0 24 24',
            width: '24',
            xmlns: SVG_NS,
        });
        assert.deepEqual(shape(svg).children, [{ tag: 'path', ns: SVG_NS, attrs: { d: 'M20 6 9 17l-5-5' }, children: [] }]);
        assert.deepEqual(page.warnings, []);
    });

    it('matches the real createIcons attribute for attribute, on the cases the dashboard has', async () => {
        const cases: Array<Record<string, string>> = [
            { 'data-lucide': 'check', 'aria-hidden': 'true', class: 'x' },
            { 'data-lucide': 'x' },                                             // the toast's close icon: no aria-hidden given
            { 'data-lucide': 'alert-triangle', 'aria-hidden': 'true' },         // an alias (TriangleAlert)
            { 'data-lucide': 'bar-chart-3', 'aria-hidden': 'true' },            // an alias with a digit
            { 'data-lucide': 'instagram', role: 'img', 'aria-label': 'IG' },    // names itself: no aria-hidden added
            { 'data-lucide': 'loader', class: 'spin  slow spin', 'aria-hidden': 'true' },
            { 'data-lucide': 'arrow-left', width: '16', 'aria-hidden': 'true' }, // the element's own attrs win
        ];
        const real = await loadReal();
        const shim = loadShim();
        for (const attrs of cases) {
            const a = real.dom.icon(attrs);
            const b = shim.dom.icon(attrs);
            real.lucide().createIcons();
            shim.lucide().createIcons({ nodes: [b] });
            assert.deepEqual(shape(b.childNodes[0]!), shape(a.childNodes[0]!), JSON.stringify(attrs));
        }
        assert.deepEqual(shim.warnings, []);
    });

    it('draws every icon in the subset exactly as the real set does', async () => {
        const real = await loadReal();
        const shim = loadShim();
        for (const name of shim.lucide().subset) {
            real.dom.icon({ 'data-lucide': name, 'aria-hidden': 'true' });
            shim.dom.icon({ 'data-lucide': name, 'aria-hidden': 'true' });
        }
        real.lucide().createIcons();
        shim.lucide().createIcons();
        assert.deepEqual(shim.dom.body.childNodes.map((d) => shape(d)), real.dom.body.childNodes.map((d) => shape(d)));
        assert.deepEqual(real.warnings, [], 'every subset name is a real lucide name');
    });

    it('renders the whole document even when given one node, as 0.577 did, and leaves svgs alone', () => {
        const page = loadShim();
        const inside = page.dom.icon({ 'data-lucide': 'check' });
        const outside = page.dom.icon({ 'data-lucide': 'x' });
        // lucide@0.577.0 has no `nodes` option: every UI.icons(node) call drew the whole page.
        page.lucide().createIcons({ nodes: [inside] });
        assert.equal(inside.childNodes[0]!.tagName, 'svg');
        assert.equal(outside.childNodes[0]!.tagName, 'svg', 'an icon outside the node is still drawn');
        const svg = inside.childNodes[0]!;
        page.lucide().createIcons({ nodes: [inside] });
        assert.equal(inside.childNodes[0], svg, 'an existing svg is not rebuilt');
        // A node not yet in the page is drawn too.
        const detached = new FakeNode('DIV', XHTML_NS);
        detached.appendChild(new FakeNode('I', XHTML_NS)).setAttribute('data-lucide', 'zap');
        page.lucide().createIcons({ nodes: [detached] });
        assert.equal(detached.childNodes[0]!.tagName, 'svg');
    });
});

describe('icon subset — a name it does not carry loads the full set once', () => {
    const scripts = (page: Page): FakeNode[] => page.dom.head.childNodes.filter((n) => n.tagName === 'SCRIPT');

    it('injects exactly one script, with the pinned src, SRI and crossorigin, and warns once', () => {
        const page = loadShim();
        assert.equal(page.lucide().subset.includes('anchor'), false, 'the test needs a name outside the subset');
        const first = page.dom.icon({ 'data-lucide': 'anchor', 'aria-hidden': 'true' });
        page.dom.icon({ 'data-lucide': 'check' });
        page.lucide().createIcons();
        page.dom.icon({ 'data-lucide': 'anvil' });
        page.lucide().createIcons();
        page.lucide().createIcons({ nodes: [first] });

        const injected = scripts(page);
        assert.equal(injected.length, 1, 'one fallback, however many calls meet a missing name');
        assert.equal(injected[0]!.getAttribute('src'), build.LUCIDE_URL);
        assert.equal(injected[0]!.getAttribute('integrity'), build.LUCIDE_SRI);
        assert.equal(injected[0]!.getAttribute('crossorigin'), 'anonymous');
        assert.equal(page.warnings.length, 1, page.warnings.join('\n'));
        assert.match(page.warnings[0]!, /anchor/);
        // The ones it has are drawn meanwhile; the missing one keeps its placeholder.
        assert.equal(first.childNodes[0]!.tagName, 'I');
        assert.equal(page.dom.body.childNodes[1]!.childNodes[0]!.tagName, 'svg');
    });

    it('then draws the missing icons with the real createIcons, and stays the entry point', () => {
        const page = loadShim();
        const shimApi = page.lucide();
        const host = page.dom.icon({ 'data-lucide': 'anchor' });
        shimApi.createIcons({ nodes: [host] });
        const [script] = scripts(page);
        assert.ok(script && script.onload, 'the fallback has an onload');

        // What the UMD does when it runs: assign window.lucide.
        const calls: Json[] = [];
        const anchor = [['path', { d: 'M12 6v16' }]];
        const realApi = {
            icons: { Anchor: anchor, Anvil: [['path', { d: 'M7 10H6' }]] },
            createIcons: (options: Json) => {
                calls.push(options);
                for (const el of (options.root as Json).querySelectorAll('[data-lucide]') as FakeNode[]) {
                    if (el.tagName === 'I') el.parentNode!.replaceChild(new FakeNode('svg', SVG_NS), el);
                }
            },
        };
        page.ctx.lucide = realApi;
        script.onload!();

        assert.equal(page.ctx.lucide, shimApi, 'window.lucide is the shim again');
        assert.equal(calls.length, 1);
        assert.equal(calls[0]!.root, page.dom.document, 'the queued icon is in the page, so the page is drawn');
        assert.equal(host.childNodes[0]!.tagName, 'svg');

        // From now on a missing name resolves from the full set, synchronously, with no new script.
        const later = page.dom.icon({ 'data-lucide': 'anvil' });
        shimApi.createIcons({ nodes: [later] });
        assert.equal(later.childNodes[0]!.tagName, 'svg');
        assert.equal(later.childNodes[0]!.getAttribute('class'), 'lucide lucide-anvil');
        assert.equal(scripts(page).length, 1);
    });

    it('a fallback that fails to load is not retried, and the placeholders stay', () => {
        const page = loadShim();
        page.dom.icon({ 'data-lucide': 'anchor' });
        page.lucide().createIcons();
        scripts(page)[0]!.onerror!();
        page.dom.icon({ 'data-lucide': 'anvil' });
        page.lucide().createIcons();
        assert.equal(scripts(page).length, 1);
    });
});

describe('icon subset — build-icons.mjs --check', () => {
    let dir = '';
    before(() => { dir = mkdtempSync(join(tmpdir(), 'icons-check-')); });
    after(() => { rmSync(dir, { recursive: true, force: true }); });

    const check = (file?: string) => spawnSync(process.execPath, ['scripts/build-icons.mjs', '--check', ...(file ? ['--file', file] : [])], { encoding: 'utf8' });

    it('passes on the committed icons.js', () => {
        const run = check();
        assert.equal(run.status, 0, run.stderr);
        assert.match(run.stdout, /icons\.js is current/);
    });

    it('fails when an icon the dashboard uses is missing from it', () => {
        const stale = join(dir, 'missing.js');
        const source = readFileSync(ICONS_JS, 'utf8');
        const line = source.split('\n').find((l) => l.startsWith('        "zap": '));
        assert.ok(line, 'zap is in the subset');
        writeFileSync(stale, source.replace(`${line}\n`, '').replace(/\],\n( {4}\};)/, ']\n$1'));
        const run = check(stale);
        assert.notEqual(run.status, 0);
        assert.match(run.stderr, /'zap' is used \(dashboard\/index\.html/);
    });

    it('fails when it carries an icon nothing uses', () => {
        const stale = join(dir, 'extra.js');
        const source = readFileSync(ICONS_JS, 'utf8');
        writeFileSync(stale, source.replace('    var ICONS = {\n', '    var ICONS = {\n        "anchor": [["path",{"d":"M12 6v16"}]],\n'));
        const run = check(stale);
        assert.notEqual(run.status, 0);
        assert.match(run.stderr, /'anchor' is in it but nothing uses it/);
    });

    it('fails when the names are right but the content was edited by hand', () => {
        const stale = join(dir, 'edited.js');
        copyFileSync(ICONS_JS, stale);
        const source = readFileSync(stale, 'utf8');
        assert.ok(source.includes('"d":"M20 6 9 17l-5-5"'), 'the check icon’s path is where the test expects it');
        writeFileSync(stale, source.replace('"d":"M20 6 9 17l-5-5"', '"d":"M20 6 9 17l-5-6"'));
        const run = check(stale);
        assert.notEqual(run.status, 0);
        assert.match(run.stderr, /content is not what the build writes/);
    });
});
